[package]
name = "tapasco-debug"
version = "0.1.0"
authors = ["zyno42 <83068959+zyno42@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.15", default-features = false, features = ['crossterm'] }
crossterm = "0.20"
tapasco = { path = "../../../libtapasco" }
snafu = "0.6"
chrono = "0.4"
log = "0.4"
env_logger = "0.8"
structopt = "0.3"
memmap = "0.7"
unicode-width = "0.1.8"
