[package]
name = "sume_clock_programmer"
version = "0.1.0"
authors = ["Jaco Hofmann <jaco.hofmann@wdc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
log = "0.4.11"
snafu = "0.6.10"
tapasco = { path = "../../../../../../runtime/libtapasco" }
volatile = "0.4.3"
